### PR TITLE
csv2rdf documentation update according to most recent changes

### PR DESCRIPTION
**Pull request by Yueqiao12Zhang**

### CODE REVIEW

**Comment by dchiller** [comment]
which README? How did you update it?

**Comment by Yueqiao12Zhang** [comment]
> which README? How did you update it?

How can github desktop automatically rename my PR to a commit message....

**Comment by dchiller** [comment]
> How can github desktop automatically rename my PR to a commit message....

I don't use GitHub desktop so I don't know. But when you open a PR, don't you do that in an interface that allows you to add a title and description to the PR?

**Comment by Yueqiao12Zhang** [comment]
It usually names the PR according to the branch name. This time it just opened with the commit message.

**Comment by dchiller** [comment]
> It usually automatically names the PR according to the branch name. This time it just opened with the commit message.

Right, but...you can edit it!

**Comment by Yueqiao12Zhang** [comment]
> > It usually automatically names the PR according to the branch name. This time it just opened with the commit message.
> 
> Right, but...you can edit it!

Am I editing it correctly now?

**Comment by dchiller** [comment]
Yeah, it looks good now :)

**Review by dchiller — APPROVED** [review]

**Pull request merged**
